---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false
dist: trusty

matrix:
  include:
    - env: ANSIBLE_VERSION=ppa:ansible/ansible
    - env: ANSIBLE_VERSION=ppa:ansible/ansible-1.9


before_install:
 - apt-get -y install software-properties-common
 - apt-add-repository -y $ANSIBLE_VERSION
 - apt-get -y update

install:
  # Install ansible
  - apt-get -y install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Provision kibana
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
