---
sudo: required
dist: trusty

matrix:
  include:
    - env: ANSIBLE_VERSION=ppa:ansible/ansible
    - env: ANSIBLE_VERSION=ppa:ansible/ansible-1.9

before_install:
 - sudo apt-get -y install software-properties-common
 - sudo apt-add-repository -y $ANSIBLE_VERSION
 - sudo apt-get -y update
 - sudo apt-get -y install ansible
 - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Provision kibana
  - ansible-playbook tests/test.yml -i tests/inventory -c local --sudo

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
