---
python: "2.7"

sudo: false
dist: trusty

matrix:
  include:
    - env: ANSIBLE_VERSION=1.9.6
    - env: ANSIBLE_VERSION=2.1.0

addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible==$ANSIBLE_VERSION

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\nhost_key_checking = False' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Provision kibana
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
